using ExaminantionSystem.Entities.Shared;
using System.ComponentModel.DataAnnotations;

namespace ExaminantionSystem.Entities.Dtos.Exam
{
    public class CreateExamDto
    {
        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [Required]
        public ExamType Type { get; set; }

        [Required]
        public int CourseId { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        [Required]
        public DateTime EndDate { get; set; }
        [Range(1, 100)]
        public int TotalQuestion { get; set; }

        public bool IsAutoGenerated { get; set; }
    }
}
