using ExaminantionSystem.Entities.Shared;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminantionSystem.Entities.Dtos.Exam
{
    public class ExamDto
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public ExamType Type { get; set; }
        public int CourseId { get; set; }
        public string CourseTitle { get; set; }
        public int Duration { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool IsAutoGenerated {  get; set; }
        public int NumberOfQuestion { get; set; }

    }
}
