using ExaminantionSystem.Entities.Shared;

namespace ExaminantionSystem.Entities.Dtos.Exam
{
    public class ManualExamDto
    {
            public int ExamId { get; set; }
            public string Title { get; set; }
            public string ExamType { get; set; }
            public int CourseId { get; set; }
            public string CourseTitle { get; set; }
            public int Duration { get; set; }
            public int QuestionCount { get; set; }
            public bool IsAutoGenerated { get; set; }
            public List<ExamQuestionDto> Questions { get; set; }
        
    }
}
