using ExaminantionSystem.Entities.Shared;
using System.ComponentModel.DataAnnotations;

namespace ExaminantionSystem.Entities.ViewModels.Exam
{
    public class CreateExamVM
    {
        [Required]
        [StringLength(100)]
        public string Title { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        [Required] 
        public ExamType Type { get; set; }
        [Required] 
        public int CourseId { get; set; }
        public int? Duration { get; set; }
        [Range(5, 20)]
        public int NumberOfQuestion { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool IsAutoGenerated { get; set; }
    }
}
