using ExaminantionSystem.Entities.Shared;

namespace ExaminantionSystem.Entities.ViewModels.Exam
{
    public class ExamWithQuestionsVM
    {
        public int ExamId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public ExamType Type { get; set; }
        public int CourseId { get; set; }
        public string CourseTitle { get; set; }
        public int? Duration { get; set; }
        public int NumberOfQuestion { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime CreatedAt { get; set; }
        public string InstructorName { get; set; }
        public int QuestionCount { get; set; }
        public List<ExamQuestionVM> Questions { get; set; }
    }
}
